### PR TITLE
Full redshift connector parameter support

### LINKED ISSUE #332: [CT-2156] [Feature] Add dbt-redshift connection methods - Auth Profile and IdP Credentials(Azure and Okta Identity Providers)
### Is this your first time submitting a feature request?

- [X] I have read the [expectations for open source contributors](https://docs.getdbt.com/docs/contributing/oss-expectations)
- [X] I have searched the existing issues, and I could not find an existing issue for this feature
- [X] I am requesting a straightforward extension of existing dbt-redshift functionality, rather than a Big Idea better suited to a discussion

### Describe the feature

Provide additional authentication methods to connect to dbt-redshift. The new code changes will allow users to connect to dbt-redshift using authentication profiles and Identity Provider (IdP) Plugins for Azure and Okta. Users will need to provide required parameters specified in [this Redshift documentation](https://docs.aws.amazon.com/redshift/latest/mgmt/odbc20-authentication-ssl.html) when configuring profiles.yml in order to authenticate using these new methods.

### Describe alternatives you've considered

_No response_

### Who will this benefit?

_No response_

### Are you interested in contributing this feature?

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by christopherscholz**
resolves #332
[docs](https://github.com/dbt-labs/docs.getdbt.com/issues/new/choose) dbt-labs/docs.getdbt.com/#
alternative for #323

### Problem

Currently not all connection methods, which the `redshift_connector` supports are currently possible with `dbt-redshift`.
Also the `connections.py` does not fully reflect the move to `redshift_connector` yet. In the past the connection methods were handled by `dbt-redshift` itself, by parsing different credentials sets based on the connections `method`. With `redshift_connector` this should now be done by `redshift_connector`.

### Solution

I have added **all** connection parameters from `redshift_connector` and removed the ConnectionFactory, as all connection methods are handled by `redshift_connector` now.

Many unit tests are now obsolete, as testing the different connection methods are now out of scope for `dbt-redshift`, but part of `redshift_connector`.

All the changes should be backwards compatible.

### Checklist

- [x] I have read [the contributing guide](https://github.com/dbt-labs/dbt-core/blob/main/CONTRIBUTING.md) and understand what's expected of me
- [x] I have run this code in development and it appears to resolve the stated issue
- [x] This PR includes tests, or tests are not required/relevant for this PR
- [ ] This PR has no interface changes (e.g. macros, cli, logs, json artifacts, config files, adapter interface, etc) or this PR has already received feedback and approval from Product or DX
  **Lots new adapter credentials options**

### CODE REVIEW

**Comment by christopherscholz** [comment]
Both unit and integration tests are successful for me.
Unfortunately I cannot tests all the different connection methods (as I don't have those set up currently), but as this is part of `redshift_connector` anyway; I guess this out of scope.

**Comment by halilduygulu** [comment]
This is great. Currently we need to set `client_protocol_version` to 0 due to [this Teleport limitation](https://github.com/gravitational/teleport/issues/29417) and looking forward to see this PR merged.

**Comment by misteliy** [comment]
Any updates here or what is currently blocking?

**Comment by halilduygulu** [comment]
+1 to @misteliy . Why are you not merging this pr?

**Comment by misteliy** [comment]
Could you please reopen as it was not resolved

**Pull request closed without merging**
