### PR TITLE
Update redshift-connector requirement from 2.0.913 to 2.0.915

### LINKED ISSUE #347: [CT-2243] [Regression] `dbt seed` doesn't work on certain cases (large row counts)
### Is this a regression in a recent version of dbt-redshift?

- [X] I believe this is a regression in dbt-redshift functionality
- [X] I have searched the existing issues, and I could not find an existing issue for this regression

### Current Behavior

I'm not 100% sure when does it happen, but I'm unable to seed CSVs that I previously was able to seed.
I'm getting the following error:

```bash
17:00:52  Finished running 14 seeds, 2 hooks in 0 hours 1 minutes and 22.77 seconds (82.77s).
17:00:52
17:00:52  Completed with 3 errors and 0 warnings:
17:00:52
17:00:52  Runtime Error in seed numeric_column_anomalies_training (data/training/numeric_column_anomalies_training.csv)
17:00:52    'h' format requires -32768 <= number <= 32767
17:00:52
17:00:52  Runtime Error in seed dimension_anomalies_training (data/training/dimension_anomalies_training.csv)
17:00:52    'h' format requires -32768 <= number <= 32767
17:00:52
17:00:52  Runtime Error in seed any_type_column_anomalies_training (data/training/any_type_column_anomalies_training.csv)
17:00:52    'h' format requires -32768 <= number <= 32767
17:00:52
17:00:52  Done. PASS=11 WARN=0 ERROR=3 SKIP=0 TOTAL=14
```

### Expected/Previous Behavior

I should be able to seed them.

### Steps To Reproduce

1. Load [this file](https://github.com/dbt-labs/dbt-redshift/files/10863640/dimension_anomalies_training.csv) to your `seeds` directory.
2. Run `dbt seed`.

Here's [another file](https://github.com/dbt-labs/dbt-redshift/files/10863648/numeric_column_anomalies_training.csv) if needed.

### Relevant log output

_No response_

### Environment

```markdown
- OS: macOS
- Python: 3.9.6
- dbt-core (working version): 1.4.0
- dbt-redshift (working version): 1.4.0
- dbt-core (regression version): 1.5.0b2
- dbt-redshift (regression version): 1.5.0b1
```

### Additional Context

_No response_

### LINKED ISSUE #456: [ADAP-564] [Regression] unpack_from requires a buffer of at least 5 bytes for unpacking 5 bytes at offset 0 (actual buffer size is 0)
### Is this a regression in a recent version of dbt-redshift?

- [X] I believe this is a regression in dbt-redshift functionality
- [X] I have searched the existing issues, and I could not find an existing issue for this regression

### Current Behavior

Some models sometimes give an error `unpack_from requires a buffer of at least 5 bytes for unpacking 5 bytes at offset 0 (actual buffer size is 0)` that is potentially related to whatever the issue is in https://github.com/aws/amazon-redshift-python-driver/issues/142

### Expected/Previous Behavior

Models run correctly.

### Steps To Reproduce

1. Use `redshift-connector` instead of `psycopg2` to connect to redshift

### Relevant log output

```shell
16:19:06  Runtime Error in model my_model (models/my_model.sql)
16:19:06    unpack_from requires a buffer of at least 5 bytes for unpacking 5 bytes at offset 0 (actual buffer size is 0)
```

### Environment

```markdown
- OS: debian 11.7
- Python: 3.8.16
- dbt-core (working version): 1.4.5
- dbt-redshift (working version): 1.4.0
- dbt-core (regression version): 1.5.0
- dbt-redshift (regression version): 1.5.1
```

### Additional Context

_No response_

### LINKED ISSUE #556: [ADAP-727] [Bug] Redshift adapter does not retry on connection timeouts
### Is this a new bug in dbt-redshift?

- [X] I believe this is a new bug in dbt-redshift
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

When running a large number of concurrent queries through the dbt-redshift adapter (e.g., by running the MetricFlow test suite using a dbt-redshift client), we observe intermittent failures with this message in the logs:

```
E           redshift_connector.error.InterfaceError: ('communication error', TimeoutError(60, 'Operation timed out'))
```

We tried changing the retry count to a larger number, and this made no apparent difference. According to the stack trace, the retry is not happening, and on further inspection we discovered that the InterfaceError is not considered a retryable exception:

https://github.com/dbt-labs/dbt-redshift/blob/main/dbt/adapters/redshift/connections.py#L335-L337

Stack trace excerpt:

```
metricflow/cli/dbt_connectors/adapter_backed_client.py:125: in query
    result = self._adapter.execute(sql=statement, auto_begin=True, fetch=True)
../../.venvs/metricflow/zJM50P7N/redshift-env/lib/python3.9/site-packages/dbt/adapters/base/impl.py:290: in execute
    return self.connections.execute(sql=sql, auto_begin=auto_begin, fetch=fetch, limit=limit)
../../.venvs/metricflow/zJM50P7N/redshift-env/lib/python3.9/site-packages/dbt/adapters/redshift/connections.py:357: in execute
    _, cursor = self.add_query(sql, auto_begin)
../../.venvs/metricflow/zJM50P7N/redshift-env/lib/python3.9/site-packages/dbt/adapters/redshift/connections.py:382: in add_query
    connection, cursor = super().add_query(
../../.venvs/metricflow/zJM50P7N/redshift-env/lib/python3.9/site-packages/dbt/adapters/sql/connections.py:57: in add_query
    self.begin()
../../.venvs/metricflow/zJM50P7N/redshift-env/lib/python3.9/site-packages/dbt/adapters/sql/connections.py:172: in begin
    self.add_begin_query()
../../.venvs/metricflow/zJM50P7N/redshift-env/lib/python3.9/site-packages/dbt/adapters/sql/connections.py:155: in add_begin_query
    return self.add_query("BEGIN", auto_begin=False)
../../.venvs/metricflow/zJM50P7N/redshift-env/lib/python3.9/site-packages/dbt/adapters/redshift/connections.py:382: in add_query
    connection, cursor = super().add_query(
../../.venvs/metricflow/zJM50P7N/redshift-env/lib/python3.9/site-packages/dbt/adapters/sql/connections.py:79: in add_query
    cursor = connection.handle.cursor()
../../.venvs/metricflow/zJM50P7N/redshift-env/lib/python3.9/site-packages/dbt/contracts/connection.py:94: in handle
    self._handle.resolve(self)
../../.venvs/metricflow/zJM50P7N/redshift-env/lib/python3.9/site-packages/dbt/contracts/connection.py:118: in resolve
    return self.opener(connection)
../../.venvs/metricflow/zJM50P7N/redshift-env/lib/python3.9/site-packages/dbt/adapters/redshift/connections.py:340: in open
    return cls.retry_connection(
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

cls = <class 'dbt.adapters.redshift.connections.RedshiftConnectionManager'>
connection = Connection(type='redshift', name='MetricFlow_request_mf_rid__9o0a7sct', state=<ConnectionState.CLOSED: 'closed'>, tran...lse, connect_timeout=None, role=None, sslmode=<UserSSLMode.prefer: 'prefer'>, retries=1, region=None, autocommit=True))
connect = <function RedshiftConnectMethodFactory.get_connect_method.<locals>.connect at 0x280207430>, logger = AdapterLogger(name='Redshift')
retryable_exceptions = [<class 'redshift_connector.error.OperationalError'>, <class 'redshift_connector.error.DatabaseError'>, <class 'redshift_connector.error.DataError'>], retry_limit = 1
retry_timeout = <function RedshiftConnectionManager.open.<locals>.exponential_backoff at 0x28026cdc0>, _attempts = 0

    @classmethod
    def retry_connection(
        cls,
        connection: Connection,
        connect: Callable[[], AdapterHandle],
        logger: AdapterLogger,
        retryable_exceptions: Iterable[Type[Exception]],
        retry_limit: int = 1,
        retry_timeout: Union[Callable[[int], SleepTime], SleepTime] = 1,
        _attempts: int = 0,
    ) -> Connection:
        """Given a Connection, set its handle by calling connect.

        The calls to connect will be retried up to retry_limit times to deal with transient
        connection errors. By default, one retry will be attempted if retryable_exceptions is set.

        :param Connection connection: An instance of a Connection that needs a handle to be set,
            usually when attempting to open it.
        :param connect: A callable that returns the appropiate connection handle for a
            given adapter. This callable will be retried retry_limit times if a subclass of any
            Exception in retryable_exceptions is raised by connect.
        :type connect: Callable[[], AdapterHandle]
        :param AdapterLogger logger: A logger to emit messages on retry attempts or errors. When
            handling expected errors, we call debug, and call warning on unexpected errors or when
            all retry attempts have been exhausted.
        :param retryable_exceptions: An iterable of exception classes that if raised by
            connect should trigger a retry.
        :type retryable_exceptions: Iterable[Type[Exception]]
        :param int retry_limit: How many times to retry the call to connect. If this limit
            is exceeded before a successful call, a FailedToConnectError will be raised.
            Must be non-negative.
        :param retry_timeout: Time to wait between attempts to connect. Can also take a
            Callable that takes the number of attempts so far, beginning at 0, and returns an int
            or float to be passed to time.sleep.
        :type retry_timeout: Union[Callable[[int], SleepTime], SleepTime] = 1
        :param int _attempts: Parameter used to keep track of the number of attempts in calling the
            connect function across recursive calls. Passed as an argument to retry_timeout if it
            is a Callable. This parameter should not be set by the initial caller.
        :raises dbt.exceptions.FailedToConnectError: Upon exhausting all retry attempts without
            successfully acquiring a handle.
        :return: The given connection with its appropriate state and handle attributes set
            depending on whether we successfully acquired a handle or not.
        """
        timeout = retry_timeout(_attempts) if callable(retry_timeout) else retry_timeout
        if timeout < 0:
            raise dbt.exceptions.FailedToConnectError(
                "retry_timeout cannot be negative or return a negative time."
            )

        if retry_limit < 0 or retry_limit > sys.getrecursionlimit():
            # This guard is not perfect others may add to the recursion limit (e.g. built-ins).
            connection.handle = None
            connection.state = ConnectionState.FAIL
            raise dbt.exceptions.FailedToConnectError("retry_limit cannot be negative")

        try:
            connection.handle = connect()
            connection.state = ConnectionState.OPEN
            return connection

        except tuple(retryable_exceptions) as e:
            if retry_limit <= 0:
                connection.handle = None
                connection.state = ConnectionState.FAIL
                raise dbt.exceptions.FailedToConnectError(str(e))

            logger.debug(
                f"Got a retryable error when attempting to open a {cls.TYPE} connection.\n"
                f"{retry_limit} attempts remaining. Retrying in {timeout} seconds.\n"
                f"Error:\n{e}"
            )

            sleep(timeout)
            return cls.retry_connection(
                connection=connection,
                connect=connect,
                logger=logger,
                retry_limit=retry_limit - 1,
                retry_timeout=retry_timeout,
                retryable_exceptions=retryable_exceptions,
                _attempts=_attempts + 1,
            )

        except Exception as e:
            connection.handle = None
            connection.state = ConnectionState.FAIL
>           raise dbt.exceptions.FailedToConnectError(str(e))
E           dbt.exceptions.FailedToConnectError: Database Error
E             ('communication error', TimeoutError(60, 'Operation timed out'))

../../.venvs/metricflow/zJM50P7N/redshift-env/lib/python3.9/site-packages/dbt/adapters/base/connections.py:271: FailedToConnectError
```

We can see at the end that the error is thrown out of the broader except block, rather than the retry handling.

### Expected Behavior

I expected these errors to be retried, but I understand why that isn't happening.

I would also expect redshift_connector to not hide this inside of an InterfaceException, that's just odd, but it is what it is.

### Steps To Reproduce

I think the only way to do this is to run lots of concurrent queries on an undersized cluster until you can trigger intermittent failures of this type. I've got a PR up that might trigger this in the MetricFlow CI as well, I'll see if it happens there. If it's just on my local machine maybe I need to do whatever that weird Redshift override thing is.

### Relevant log output

_No response_

### Environment

```markdown
- OS: Mac OS X Ventura 13.4.1 (c)
- Python: 3.9.latest
- dbt-core: 1.6.0rc1
- dbt-redshift: 1.6.0rc1
```

### Additional Context

I am not using dbt proper, just the adapter. See https://github.com/dbt-labs/metricflow/pull/678

### PR DESCRIPTION
**Pull request by soksamnanglim**
resolves #556 ,  resolves #456 ,  resolves #347 

### Problem

 
Updates the version to new release of redshift-connector. [Here's the relevant changelog for 2.0.914](https://github.com/aws/amazon-redshift-python-driver/blob/master/CHANGELOG.md#v20914-2023-09-11)

here are the relevant PRs that improve error messaging in the drive
- https://github.com/aws/amazon-redshift-python-driver/pull/179
- https://github.com/aws/amazon-redshift-python-driver/pull/185
- https://github.com/aws/amazon-redshift-python-driver/pull/187
### Solution

The new release:
- maps socket timeout errors to OperationalError instead of InterfaceError
- maps bind parameter limitation errors to DataError `Prepared statement exceeds bind parameter limit 32767.` instead of struct.error `'h' format requires -32768 <= number <= 32767`
- maps server side socket closing errors to InterfaceError `BrokenPipe: server socket closed.` instead of struct.error `unpack_from requires a buffer of at least 5 bytes for unpacking 5 bytes at offset 0 (actual buffer size is 0)`

### Checklist

- [x] I have read [the contributing guide](https://github.com/dbt-labs/dbt-core/blob/main/CONTRIBUTING.md) and understand what's expected of me
- [x] I have run this code in development and it appears to resolve the stated issue
- [x] This PR includes tests, or tests are not required/relevant for this PR
- [x] This PR has no interface changes (e.g. macros, cli, logs, json artifacts, config files, adapter interface, etc) or this PR has already received feedback and approval from Product or DX
- [ ] Run manual tests (planning on doing this soon)

### CODE REVIEW

**Comment by soksamnanglim** [comment]
converted this PR to a draft, as I still need to conduct manual testing, would love your recommendations for smoke tests!

**Comment by mikealfare** [comment]
All of the tests failed or raised an error with an exception similar to the following:

<details>
  <summary>Click me</summary>

```
[gw1] linux -- Python 3.8.18 /home/runner/work/dbt-redshift/dbt-redshift/.tox/integration-redshift/bin/python

self = <logbook.compat.LoggingCompatRecord object at 0x7f1799a9de20>

    @cached_property
    def message(self):
        """The formatted message."""
        if not (self.args or self.kwargs):
            return self.msg
        try:
            try:
>               return self._format_message(self.msg, *self.args,
                                            **self.kwargs)
E                                           TypeError: _format_message() keywords must be strings

/home/runner/work/dbt-redshift/dbt-redshift/.tox/integration-redshift/lib/python3.8/site-packages/logbook/base.py:554: TypeError

During handling of the above exception, another exception occurred:

self = <pytest_logbook.LogbookManager object at 0x7f17c89e34f0>
item = <Function test_redshift_simple_seed_with_column_override_redshift>

    @pytest.hookimpl(hookwrapper=True)
    def pytest_runtest_call(self, item):
        """Enable logbook capturing during test call."""
        with self.capturing(item, 'call'):
>           yield

/home/runner/work/dbt-redshift/dbt-redshift/.tox/integration-redshift/lib/python3.8/site-packages/pytest_logbook.py:97: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/contextlib.py:120: in __exit__
    next(self.gen)
/home/runner/work/dbt-redshift/dbt-redshift/.tox/integration-redshift/lib/python3.8/site-packages/pytest_logbook.py:74: in capturing
    '\n'.join(handler.formatted_records))
/home/runner/work/dbt-redshift/dbt-redshift/.tox/integration-redshift/lib/python3.8/site-packages/logbook/handlers.py:1031: in formatted_records
    self._formatted_records = [self.format(r) for r in self.records]
/home/runner/work/dbt-redshift/dbt-redshift/.tox/integration-redshift/lib/python3.8/site-packages/logbook/handlers.py:1031: in <listcomp>
    self._formatted_records = [self.format(r) for r in self.records]
/home/runner/work/dbt-redshift/dbt-redshift/.tox/integration-redshift/lib/python3.8/site-packages/logbook/handlers.py:195: in format
    return self.formatter(record, self)
/home/runner/work/dbt-redshift/dbt-redshift/.tox/integration-redshift/lib/python3.8/site-packages/logbook/handlers.py:387: in __call__
    line = self.format_record(record, handler)
/home/runner/work/dbt-redshift/dbt-redshift/.tox/integration-redshift/lib/python3.8/site-packages/logbook/handlers.py:371: in format_record
    return self._formatter.format(record=record, handler=handler)
/home/runner/work/dbt-redshift/dbt-redshift/.tox/integration-redshift/lib/python3.8/site-packages/logbook/helpers.py:283: in __get__
    value = self.func(obj)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <logbook.compat.LoggingCompatRecord object at 0x7f1799a9de20>

    @cached_property
    def message(self):
        """The formatted message."""
        if not (self.args or self.kwargs):
            return self.msg
        try:
            try:
                return self._format_message(self.msg, *self.args,
                                            **self.kwargs)
            except UnicodeDecodeError:
                # Assume an unicode message but mixed-up args
                msg = self.msg.encode('utf-8', 'replace')
                return self._format_message(msg, *self.args, **self.kwargs)
            except (UnicodeEncodeError, AttributeError):
                # we catch AttributeError since if msg is bytes,
                # it won't have the 'format' method
                if (sys.exc_info()[0] is AttributeError
                        and (PY2 or not isinstance(self.msg, bytes))):
                    # this is not the case we thought it is...
                    raise
                # Assume encoded message with unicode args.
                # The assumption of utf8 as input encoding is just a guess,
                # but this codepath is unlikely (if the message is a constant
                # string in the caller's source file)
                msg = self.msg.decode('utf-8', 'replace')
                return self._format_message(msg, *self.args, **self.kwargs)
    
        except Exception:
            # this obviously will not give a proper error message if the
            # information was not pulled and the log record no longer has
            # access to the frame.  But there is not much we can do about
            # that.
            e = sys.exc_info()[1]
            errormsg = ('Could not format message with provided '
                        'arguments: {err}\n  msg={msg!r}\n  '
                        'args={args!r} \n  kwargs={kwargs!r}.\n'
                        'Happened in file {file}, line {lineno}').format(
                err=e, msg=self.msg, args=self.args,
                kwargs=self.kwargs, file=self.filename,
                lineno=self.lineno
            )
            if PY2:
                errormsg = errormsg.encode('utf-8')
>           raise TypeError(errormsg)
E           TypeError: Could not format message with provided arguments: _format_message() keywords must be strings
E             msg='connection.redshift_types=%s'
E             args=() 
E             kwargs=defaultdict(<function <lambda> at 0x7f17c8279f70>, {<RedshiftOID.ABSTIME: 702>: (1, <function abstime_recv at 0x7f17c8270f70>), <RedshiftOID.BOOLEAN: 16>: (1, <function bool_recv at 0x7f17c8270700>), <RedshiftOID.NAME: 19>: (1, <function text_recv at 0x7f17c8270670>), <RedshiftOID.BIGINT: 20>: (1, <function int8_recv at 0x7f17c8270820>), <RedshiftOID.SMALLINT: 21>: (1, <function int2_recv at 0x7f17c82708b0>), <RedshiftOID.INT2VECTOR: 22>: (0, <function vector_in at 0x7f17c8270940>), <RedshiftOID.INTEGER: 23>: (1, <function int4_recv at 0x7f17c82709d0>), <RedshiftOID.REGPROC: 24>: (1, <function oid_recv at 0x7f17c8270af0>), <RedshiftOID.TEXT: 25>: (1, <function text_recv at 0x7f17c8270670>), <RedshiftOID.OID: 26>: (1, <function oid_recv at 0x7f17c8270af0>), <RedshiftOID.XID: 28>: (0, <function int_in at 0x7f17c8270a60>), <RedshiftOID.JSON: 114>: (0, <function json_in at 0x7f17c8270b80>), <RedshiftOID.REAL: 700>: (1, <function float4_recv at 0x7f17c8270c10>), <RedshiftOID.FLOAT: 701>: (1, <function float8_recv at 0x7f17c8270ca0>), <RedshiftOID.UNKNOWN: 705>: (1, <function text_recv at 0x7f17c8270670>), <RedshiftOID.SMALLINT_ARRAY: 1005>: (1, <function array_recv_binary at 0x7f17c8279ca0>), <RedshiftOID.INTEGER_ARRAY: 1007>: (1, <function array_recv_binary at 0x7f17c8279ca0>), <RedshiftOID.TEXT_ARRAY: 1009>: (1, <function array_recv_binary at 0x7f17c8279ca0>), <RedshiftOID.CHAR_ARRAY: 1002>: (1, <function array_recv_binary at 0x7f17c8279ca0>), <RedshiftOID.OID_ARRAY: 1028>: (1, <function array_recv_binary at 0x7f17c8279ca0>), <RedshiftOID.ACLITEM: 1033>: (1, <function text_recv at 0x7f17c8270670>), <RedshiftOID.ACLITEM_ARRAY: 1034>: (1, <function array_recv_binary at 0x7f17c8279ca0>), <RedshiftOID.VARCHAR_ARRAY: 1015>: (1, <function array_recv_binary at 0x7f17c8279ca0>), <RedshiftOID.REAL_ARRAY: 1021>: (1, <function array_recv_binary at 0x7f17c8279ca0>), <RedshiftOID.CHAR: 18>: (1, <function text_recv at 0x7f17c8270670>), <RedshiftOID.BPCHAR: 1042>: (1, <function text_recv at 0x7f17c8270670>), <RedshiftOID.STRING: 1043>: (1, <function text_recv at 0x7f17c8270670>), <RedshiftOID.DATE: 1082>: (1, <function date_recv_binary at 0x7f17c8279790>), <RedshiftOID.TIME: 1083>: (1, <function time_recv_binary at 0x7f17c82795e0>), <RedshiftOID.TIMESTAMP: 1114>: (1, <function timestamp_recv_integer at 0x7f17c8270ee0>), <RedshiftOID.TIMESTAMPTZ: 1184>: (1, <function timestamptz_recv_integer at 0x7f17c8279160>), <RedshiftOID.TIMETZ: 1266>: (1, <function timetz_recv_binary at 0x7f17c8279550>), <RedshiftOID.INTERVAL: 1186>: (1, <function interval_recv_integer at 0x7f17c82794c0>), <RedshiftOID.NUMERIC: 1700>: (1, <function numeric_in_binary at 0x7f17c8279280>), <RedshiftOID.GEOGRAPHY: 3001>: (1, <function geographyhex_recv at 0x7f17c8279dc0>), <RedshiftOID.GEOMETRY: 3000>: (0, <function text_recv at 0x7f17c8270670>), <RedshiftOID.GEOMETRYHEX: 3999>: (0, <function geometryhex_recv at 0x7f17c8279e50>), <RedshiftOID.SUPER: 4000>: (0, <function text_recv at 0x7f17c8270670>), <RedshiftOID.VARBYTE: 6551>: (0, <function text_recv at 0x7f17c8270670>)}).
E           Happened in file /home/runner/work/dbt-redshift/dbt-redshift/.tox/integration-redshift/lib/python3.8/site-packages/redshift_connector/core.py, line 851

/home/runner/work/dbt-redshift/dbt-redshift/.tox/integration-redshift/lib/python3.8/site-packages/logbook/base.py:590: TypeError
```

</details>

Have you tried running this locally?

**Comment by dataders** [comment]
piggybacking on top of @mikealfare. see [this excerpt of the test log](https://github.com/dbt-labs/dbt-redshift/actions/runs/6177062149/job/16767367339?pr=601#step:7:442). the error is raised by `logbook` a dependency of redshift_connector by a call to `_logger.debug()` on [redshift_connector/core.py#L851](https://github.com/aws/amazon-redshift-python-driver/blob/a898554b4dde2cdc6a1c6214eb43b92e36540bcf/redshift_connector/core.py#L851) which was introduce as a part of this latest release ([commit `858abad`](https://github.com/aws/amazon-redshift-python-driver/commit/858abadae4a013e96fd88f801260bd856ee3b34e))

```py
_logger.debug("connection.redshift_types=%s", self.redshift_types)
```

The error message is complaining that `self.redshift_types` is not a string but instead (unsurprisingly) a struct of all the `redshift_types`.

**Comment by soksamnanglim** [comment]
Hi @mikealfare, thanks for testing! I ran the tests in a venv using tox and all tests passed. What should I do to reproduce this locally?

Thanks for the briefing @dataders, I'll take a look 🙂

**Comment by mikealfare** [comment]
@soksamnanglim Yeah, just running `tox` runs the unit tests (default environment). You should be able to do any of the following, depending on your preference:

```
make integration

# py38 below can be one of {py38,py39,py310,py311}
tox -e py38-redshift

# you can throw a -v or -vv at the end below to get more verbose output
python -m pytest tests/functional
```

**Comment by dataders** [comment]
my hunch is that `self.redshift_types` needs to be explicitly cast to string, i.e. with `str()`
```py
_logger.debug("connection.redshift_types=%s", str(self.redshift_types))
```

**Comment by soksamnanglim** [comment]
The following is a paraphrase from Brooke:
redshift-connector doesn't have actually have a dependency on logbook (we use python std logging). Maybe this type of log statement is incompatible with logbook and causes this error? It seems logbook is a dependency in`dev-requirements.txt`, is there a logbook setting we could potentially change to fix this?  

Rs connector tested logging, however we didn't do any compatibility testing with logbook.

**Comment by mikealfare** [comment]
Agreed that this is not from `pytest-logbook`, and that `pytest-logbook` is used in `dbt-redshift` and not `redshift-connector`. However, the error appears to be thrown by the line that @dataders identified.

It looks like the arguments in `.debug(msg, *args, **kwargs)` need to be "stringifyable" as they get passed into `msg.format(*args, **kwargs)`: https://docs.python.org/3/library/logging.html#logging.Logger.debug. Do we know that the dictionary `self.redshift_types` has keys (`RedshiftOID.*`) and values (`Tuple[{FC_BINARY, FC_TEXT},redshift_connector.utils.*]`) that have __str__ defined?

**Comment by soksamnanglim** [comment]
Hi dbt team! 

The python driver release came out today, so I updated this CR to bump the version to 2.0.915. 
All integration tests pass except for this one:
`TestRedshiftMaterializedViewsBasic.test_table_replaces_materialized_view `

**Comment by dataders** [comment]
yo @soksamnanglim -- thanks for the follow-up! The end is in sight.

Two questions:
1. Did you adjust something to have the `redshift_connector.core` DEBUG logs added? I don't remember seeing them before
2. Are you seeing a local failure of `TestRedshiftMaterializedViewsBasic.test_table_replaces_materialized_view` as well?

**Comment by soksamnanglim** [comment]
1. The 2.0.915 release only included the logging fix and lints to the codebase. Perhaps the [logging improvements in 2.0.914](https://github.com/aws/amazon-redshift-python-driver/commit/858abadae4a013e96fd88f801260bd856ee3b34e) are responsible for the debug logs.
2. Yes, however, the entire test suite for `TestRedshiftMaterializedViewsBasic` and `TestRedshiftMaterializedViewChangesApply/Continue/Fail` fail locally.

**Comment by soksamnanglim** [comment]
Update! I ran integration tests with py38 locally and all the materialized view tests pass with version 2.0.915.
dbt-redshift commit used was [4213f7d9676d8aefa819bd8b393d40743699819c](https://github.com/dbt-labs/dbt-redshift/commit/4213f7d9676d8aefa819bd8b393d40743699819c)

Hopefully we can get this resolved soon 🙂

**Review by colin-rogers-dbt — APPROVED** [review]

**Pull request merged**
