### PR TITLE
[Backport] #80 to unstick releases for adapters

### PR DESCRIPTION
**Pull request by McKnight-42**
resolves #80 second half in which we need to control what branches our pr's tests against

### Description
Pulls in #80 to latest branch to clear up tests against wrong branches. 

### Checklist

- [x] I have signed the [CLA](https://docs.getdbt.com/docs/contributor-license-agreements)
- [x] I have run this code in development and it appears to resolve the stated issue
- [ ] This PR includes tests, or tests are not required/relevant for this PR
- [x] I have updated the `CHANGELOG.md` and added information about my change to the "dbt-redshift next" section.

### CODE REVIEW

**Comment by McKnight-42** [comment]
Was curious if as this is the newest of the things that will be backported if removing the mentions of previous changes that will be added to back port ex. #52 and #63.

**Comment by leahwicz** [comment]
It looks like we are still failing tests with this updated workflow. Not sure what is wrong but let's dig into it and see if we really have a bug in the `1.0.latest` branches or if its the CI

**Comment by McKnight-42** [comment]
thoughts on why the unit test for `tests/unit/test_redshift_adapter.py` is failing: trying to look into a key difference between how agate.Number and agate.data_type.number.Number work both seem to describe how a integer should work in a table/table creation.

**Comment by McKnight-42** [comment]
The `docs_generate` tests are failing due to testing against and looking for unique_key as a list changes made here [#70](https://github.com/dbt-labs/dbt-redshift/pull/70/files)

**Comment by leahwicz** [comment]
@McKnight-42 I think you are on the right track here with the dev_requirements change!

**Comment by McKnight-42** [comment]
Closed in favore of https://github.com/dbt-labs/dbt-redshift/pull/89

**Pull request closed without merging**
